language: objective-c
 
branches:
 only:
 - master
 
xcode_project: TravisTest.xcodeproj
xcode_scheme: TravisTestUITests
osx_image: osx_image: xcode7.2
xcode_sdk: iphonesimulator8.3 
 
script:
- xcodebuild clean build test -project TravisTest.xcodeproj -scheme TravisTestUITests
