language: objective-c

before_install:
  - brew update
  - brew upgrade xctool
 
xcode_project: TravisTest.xcodeproj
xcode_scheme: TravisTest
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.2
 
script:
  - xctool -project TravisTest.xcodeproj -scheme TravisTest -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -project TravisTest.xcodeproj -scheme TravisTestTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
