language: objective-c

before_install:
  - brew update
  - brew upgrade xctool
 
xcode_project: TravisTest.xcodeproj
xcode_scheme: TravisTest
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.2
 
install:
  - xcodebuild -workspace TravisTest.xcodeproj -scheme TravisTestUITests -destination 'platform=OS X,arch=x86_64' clean build | xcpretty -c || true

script:
  - xcodebuild -workspace TravisTest.xcodeproj -scheme TravisTestUITests -destination 'platform=OS X,arch=x86_64' test
